#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/OnTask/ontask 80
    chown root /opt/OnTask/chrome-sandbox
    chmod 4755 /opt/OnTask/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser ontask.desktop && sudo update-alternatives --config x-www-browser to set OnTask as your default browser."
    ln -sf /opt/OnTask/ontask /usr/bin/ontask
fi
