#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --remove x-www-browser /opt/OnTask/ontask
    echo "OnTask has been removed from update-alternatives list."
    echo "If you set OnTask as your default browser, please select another browser manually."
    echo "The following command is:"
    echo "xdg-settings set default-web-browser browser-name.desktop"
fi
